apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app-exercise1
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/kind/exercise1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system